name = "we0-index-proxy"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "public"

[env.production]
name = "we0-index-proxy"

[env.production.vars]
ORIGIN_URL = "https://your-backend-url.com"  # Replace with your actual backend URL

[[env.production.pages_functions]]
directory = "functions"

[env.production.pages]
output_dir = "public"