name = "rapidtools-platform"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "public"

[env.production]
name = "rapidtools-platform"

[env.production.vars]
ORIGIN_URL = "https://api.rapidtools.dev"  # Replace with your actual backend URL

# Pages Functions configuration
[env.production.pages_functions]
directory = "functions"

[env.production.pages]
output_dir = "public"

# Preview environment
[env.preview]
name = "rapidtools-platform-preview"

[env.preview.vars]
ORIGIN_URL = "https://api.rapidtools.dev"  # Replace with your actual backend URL

[env.preview.pages_functions]
directory = "functions"

[env.preview.pages]
output_dir = "public"