name: Deploy Cloudflare Pages Functions

on:
  push:
    branches:
      - main
      - cursor/migrate-project-to-cloudflare-pages-e9d9
    paths:
      - 'functions/**'
      - 'wrangler.toml'

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Wrangler
        uses: cloudflare/setup-wrangler-action@v3
        
      - name: Deploy Functions
        run: |
          wrangler pages deploy public \
            --project-name=we0-index-proxy \
            --branch=main \
            --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}